CREATE TABLE uplatnica (
    id SERIAL PRIMARY KEY,
    ime VARCHAR(255) NOT NULL,
    adresa VARCHAR(255) NOT NULL,
    telefon VARCHAR(20) NOT NULL,
    svrha_doznake VARCHAR(255) NOT NULL,
    primalac VARCHAR(255) NOT NULL,
    mjesto VARCHAR(255) NOT NULL,
    datum_uplate DATE NOT NULL,
    potpis_nalogodavca VARCHAR(255) NOT NULL,
    pecat_banke VARCHAR(255),
    potpis_ovlastenog_lica VARCHAR(255) NOT NULL,
    racun_posiljaoca VARCHAR(16) NOT NULL,
    racun_primaoca VARCHAR(16) NOT NULL,
    iznos NUMERIC(10, 2) NOT NULL,
    hitno BOOLEAN,
    broj_poreskog_obveznika VARCHAR(13),
    vrsta_prihoda VARCHAR(6),
    opcina VARCHAR(3),
    poziv_na_broj VARCHAR(10),
    porezni_period_od DATE,
    porezni_period_do DATE,
    budzetska_organizacija VARCHAR(7)
);
